# Generated by Django 2.1 on 2018-08-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('main', '0002_remove_info_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='site',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
