# Generated by Django 2.1 on 2018-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_me_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='site',
        ),
    ]
