# Generated by Django 2.1 on 2018-09-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_galleryimage_uploaded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_date',
        ),
    ]
