# Generated by Django 2.1 on 2018-09-30 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_comment_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
