# Generated by Django 2.1 on 2018-12-15 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('lastUnblockedLogin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
